version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  data: